/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INFTCollectionManager } from "./INFTCollectionManager";
export type { ISalesService } from "./ISalesService";
