/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SalesService } from "./SalesService";
export type { SalesServiceERC20 } from "./SalesServiceERC20";
