/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SalesService__factory } from "./SalesService__factory";
export { SalesServiceERC20__factory } from "./SalesServiceERC20__factory";
