/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockErc721 from "./MockERC721";
export type { mockErc721 };
export type { MockERC20 } from "./MockERC20";
export type { MockUniFactory } from "./MockUniFactory";
export type { MockUniRouter } from "./MockUniRouter";
export type { MockWeth } from "./MockWeth";
