/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INFTCollectionManager__factory } from "./INFTCollectionManager__factory";
export { ISalesService__factory } from "./ISalesService__factory";
